feat: add flag to not open the browser automatically
inovex/CalendarSync pull request #159
Opened 2024-06-16 12:14 UTC by alxndr13

Sometimes i want to authenticate using an incognito window, but calendarsync opens the auth dialog in the last recent window i used. To make sure i can select which browser, window or profile i want to use for the authentication, i can now add the flag `--open-browser false` to get a link which can be copied to the browser or window the user selects.

2024-07-05 15:56 UTC, MichaelEischer requested changes
There's something missing here, the `openBrowser` argument is just passed along, but never used.

2024-07-05 15:56 UTC, MichaelEischer commented on internal/adapter/outlook_http/adapter.go
> -func (c *CalendarAPI) Initialize(ctx context.Context, config map[string]interface{}) error {
The variable is never used.

2024-07-05 15:56 UTC, MichaelEischer commented on internal/adapter/google/adapter.go
> +func (c *CalendarAPI) Initialize(ctx context.Context, openBrowser bool, config map[string]interface{}) error {
The variable is never used.

2024-07-10 09:38 UTC, alxndr13 commented
@MichaelEischer thanks for the heads up. I had some changes that I hadn't committed yet. They are committed now, please take a look. :) 

I was surprised when you mentioned that this variable wasn't used. I've been using my custom build for four weeks without issues, but I guess I need to commit my changes. 😄

2024-07-10 18:27 UTC, MichaelEischer approved these changes

2024-07-10 18:27 UTC, merged